### ISSUE TITLE
[Outsourcing] 測試流程 - JUnit 單元測試 | NT$1500 | 完成日期 : 6/22

### ISSUE THREAD

**Issue by eGroupTeam** [eGroupTeam/Outsourcing#2]

**Comment by LaiTaiYuan** [comment]
相關資源參考

- [JUnit單元測試](https://laitaiyuan1.gitbooks.io/egroup/content/%E5%96%AE%E5%85%83%E6%B8%AC%E8%A9%A6.html)

**Comment by eGroupTeam** [comment]
https://paper.dropbox.com/doc/Amazon-Linux-Ubuntu-Jenkins--A2KeZ_BisIglKCVvRqgqTsZ2Ag-Dz2egkF4ffXUB5S2abM0k
